version: 1.5.{build}
build:
  verbosity: minimal

environment:
    matrix:
    # Qt 5.9
    - QTDIR: C:\Qt\5.9\msvc2015_64
      CMD_VCVARSALL: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall" x64'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    # Qt 5.10
    - QTDIR: C:\Qt\5.10\msvc2017_64
      CMD_VCVARSALL: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    # Qt 5.11
    - QTDIR: C:\Qt\5.11\msvc2017_64
      CMD_VCVARSALL: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    # Qt 5.12
    - QTDIR: C:\Qt\5.12\msvc2017_64
      CMD_VCVARSALL: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

branches:
  only:
    - master
install:
  - call %CMD_VCVARSALL%
  - set PATH=%PATH%;%QTDIR%\bin
build_script:
  - qmake %APPVEYOR_BUILD_FOLDER%\arsenic.pro -spec win32-msvc CONFIG+=x86_64
  - qmake %APPVEYOR_BUILD_FOLDER%\src\zlib\zlib.pro -spec win32-msvc CONFIG+=x86_64
  - qmake %APPVEYOR_BUILD_FOLDER%\src\quazip\quazip.pro -spec win32-msvc CONFIG+=x86_64
  - qmake %APPVEYOR_BUILD_FOLDER%\src\tests\tests.pro -spec win32-msvc CONFIG+=x86_64
  - qmake %APPVEYOR_BUILD_FOLDER%\src\botan\botan.pro -spec win32-msvc CONFIG+=x86_64
  - nmake

