version: 0.9.{build}

environment:
  matrix:
    - QTDIR: C:\Qt\5.13.2\mingw73_64
      cname: mingw

configuration:
  - release

install:
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %cname%==mingw set make=mingw32-make.exe
  - if %cname%==mingw g++ --version
  - if %cname%==mingw %make% --version
  - if not %cname%==mingw call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
  - if not %cname%==mingw set make=nmake.exe
  - if not %cname%==mingw %make% /? > nul
  - if %cname%==mingw set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\shared

before_build:
    # Prepare the out-of-source build directory.
    - cd %APPVEYOR_BUILD_FOLDER%
    - qmake arsenic.pro

build_script:
  - '%make%'
  #- cd %APPVEYOR_BUILD_FOLDER%/release
  #- arsenic.exe -e -p mysuperbadpassphrase -n myemail@cool.com pixmaps/test.jpg
  #- arsenic.exe -d -p mysuperbadpassphrase pixmaps/test.jpg.arsenic

after_build:
  - if [%CONFIGURATION%]==[release] (
    cd %APPVEYOR_BUILD_FOLDER% &&
    mkdir release &&
    cd release &&
    xcopy %APPVEYOR_BUILD_FOLDER%\src\arsenic\arsenic.exe %APPVEYOR_BUILD_FOLDER%\release\ &&
    windeployqt arsenic.exe
    )

artifacts:
  - path: \release\arsenic-*.exe
  - path: release
    type: zip
