image: Visual Studio 2017

environment:
  matrix:
  - QTPATH: C:\Qt\5.13.0\msvc2017_64
    PLATFORM: amd64
    COMPILER: msvc
    VSVER: 15

clone_depth: 1

init:
  - set TAG_NAME=Arsenic

build_script:
  - call "build_windows_msvc.cmd"

