branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.10\mingw53_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;
build_script:
  - qmake arsenic.pro
  - mingw32-make
after_build:
  - rm release/*.o
  - rm release/*.cpp

artifacts:
  - path: Output\arsenic-*.exe
  - path: release
    type: zip
