version: 1.5.{build}
build:
  verbosity: minimal

environment:
    matrix:
    # MinGW GCC
    - CC: MinGW
      PLATFORM: x86_amd64
      QTDIR: C:\Qt\5.13.2
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      MAKE_TOOL: mingw32-make
      TARGET_CC: gcc
    # Qt 5.9
    - QTDIR: C:\Qt\5.9\msvc2015_64
      CMD_VCVARSALL: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall" x64'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

branches:
  only:
    - master
install:
  - call %CMD_VCVARSALL%
  - set PATH=%PATH%;%QTDIR%\bin
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\
  - qmake
  - make

