environment:
  matrix:
    - QTDIR: C:\Qt\5.11\msvc2017_64
      CMD_VCVARSALL: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSVC_PLATFORM: "x64"

configuration:
  - release

# Get the project submodules
# Set the environment variables and paths to make
install:
  - git submodule update --init --recursive
  - dir %QTDIR%
  - call %CMD_VCVARSALL%
  - set PATH=%PATH%;%QTDIR%\bin;%APPVEYOR_BUILD_FOLDER%\OpenCV\bin

# Run qmake
before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - qmake arsenic.pro


# Build the projects
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - nmake

