sudo: required

language: cpp

compiler:
  - gcc
  - clang

arch:
  packages:
  - qt5
  script:
  - qmake
  - make

script:
- "curl -s https://github.com/mikkeloscar/arch-travis/blob/master/arch-travis.sh | bash"
