sudo: required

language: cpp

compiler:
  - gcc
  - clang

arch:
  packages:
  - qt5
  script:
  - qmake
  - make

script:
- "curl -s https://raw.githubusercontent.com/Antidote1911/arch-travis/master/arch-travis.sh | bash"
