sudo: required
dist: trusty

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt dist-upgrade
 - sudo apt install ubuntu-sdk-ide
 - sudo apt-get update -qq
 - sudo apt-get install qt5-default qttools5-dev-tools #install necessary Qt files

script:
 - qmake -project
 - qmake arsenic.pro
 - make
