sudo: required
language: cpp

compiler:
  - clang
  - gcc

dist: Bionic

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

install:
  - sudo apt-get update -qq
  - sudo apt-get install clang

before_script:
  - export PATH=$PATH:/opt/qt58/bin

script:
 - if [ "${CC}" == "clang" ]; then export CC="clang" ; export CXX="clang++" ; echo "Rexported clang" ; fi
 - if [ "${CC}" == "gcc" ]; then export CC="g++" ; export CXX="g++" ; echo "Rexported gcc" ; fi
 - qmake --version
 - qmake -project
 - qmake arsenic.pro -spec linux-$CC -std=c++17
 - make

notifications:
email: none
