language: cpp
sudo: required
dist: trusty

addons:
#  coverity_scan:
#    project:
#      name: "AraHaan/bin2c"
#      version: 0.15.0
#      description: "bin2c Conversion Tool."

    apt:
        sources:
            - ubuntu-toolchain-r-test
            - beineri/opt-qt58-trusty
            - llvm-toolchain-precise-3.9
        packages:
            - g++-6
            - clang-3.9

    notification_email: none
#    build_command_prepend: " -O3 -std=c++14 bin2c.cpp -o bin2c"
#    build_command: $CXX
#    branch_pattern: coverity_scan

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-6

    - compiler: clang
      env: COMPILER=clang++-3.9

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo apt-get -qq update;    fi

before_script:
    - if [ "$COMPILER" = "g++-6"        ]; then export CXX="g++-6" CC="gcc-6";              fi
    - if [ "$COMPILER" = "clang++-3.9"  ]; then export CXX="clang++-3.9" CC="clang-3.9";    fi
    
script:
 - qmake --version
 - qmake -project
 - qmake arsenic.pro
 - make
