sudo: required
language: cpp

compiler:
  - gcc
  - clang
  
dist: trusty

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:beineri/opt-qt58-trusty
  - sudo apt-get update -qq
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  - sudo apt-get install -qq g++-5 # C++14
  - sudo apt-get install -qq cmake qt58base qt58declarative
  - source /opt/qt58/bin/qt58-env.sh

before_script:
  - export PATH=$PATH:/opt/qt58/bin

script:
 - qmake --version
 - qmake -project
 - qmake arsenic.pro
 - make

notifications:
email: antidote1911@gmail.com
