sudo: required
language: cpp

compiler:
  - clang
  - gcc
          
dist: trusty

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  
install:
  - sudo apt-get install -qq g++-5 # C++14
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo add-apt-repository -y ppa:beineri/opt-qt58-trusty
  - sudo apt-get update -qq
  - sudo apt-get install clang


script:
 - if [ "${CC}" == "clang" ]; then export CC="clang" ; export CXX="clang++" ; echo "Rexported clang" ; fi
 - if [ "${CC}" == "gcc" ]; then export CC="g++" ; export CXX="g++" ; echo "Rexported gcc" ; fi
 - qmake --version
 - qmake -project
 - qmake arsenic.pro -spec linux-$CC
 - make

notifications:
email: none