language: cpp
compiler:
  - clang
  - gcc

dist: bionic

services:
  - xvfb

before_install:
  - sudo apt-get update -qq

install:
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

before_script:
  - export DISPLAY=:99.0

script:
  - if [ "${CC}" == "clang" ]; then export CC="clang" ; export CXX="clang++" ; echo "Rexported clang" ; fi
  - if [ "${CC}" == "gcc" ]; then export CC="g++" ; export CXX="g++" ; echo "Rexported gcc" ; fi
  - qmake -qt=qt5 arsenic.pro -spec linux-$CC
  - make
  - sudo cp thirdparty/zxcvbn/libzxcvbn.so.1.0.0 /usr/lib/libzxcvbn.so.1.0.0
  - sudo cp thirdparty/zxcvbn/libzxcvbn.so.1.0 /usr/lib/libzxcvbn.so.1.0
  - sudo cp thirdparty/zxcvbn/libzxcvbn.so.1 /usr/lib/libzxcvbn.so.1
  - sudo cp thirdparty/zxcvbn/libzxcvbn.so /usr/lib/libzxcvbn.so
  - sudo cp arscore/libarscore.so.1.0.0 /usr/lib/libarscore.so.1.0.0
  - sudo cp arscore/libarscore.so.1.0 /usr/lib/libarscore.so.1.0
  - sudo cp arscore/libarscore.so.1 /usr/lib/libarscore.so.1
  - sudo cp arscore/libarscore.so /usr/lib/libarscore.so
  - arsenic/./arsenic -e -p mysuperbadpassphrase src/arsenic/pixmaps/test.jpg
  - arsenic/./arsenic -d -p mysuperbadpassphrase src/arsenic/pixmaps/test.jpg.arsenic
  - ./tests/tests

