sudo: required
dist: trusty

before_install:
 - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update
 - sudo apt-get install qt5-default qttools5-dev-tools #install necessary Qt files

script:
 - qmake -project
 - qmake arsenic.pro
 - make
