sudo: required
language: cpp

compiler:
  - clang
  - gcc

dist: bionic

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake


script:
 - if [ "${CC}" == "clang" ]; then export CC="clang" ; export CXX="clang++" ; echo "Rexported clang" ; fi
 - if [ "${CC}" == "gcc" ]; then export CC="g++" ; export CXX="g++" ; echo "Rexported gcc" ; fi
 - qmake --version
 - qmake -project
 - qmake arsenic.pro -spec linux-$CC
 - make

notifications:
email: none
