---
language: cpp
compiler: gcc
dist: bionic

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

script:
  - qmake
  - make
  - ./arsenic
