language: cpp
compiler:
  - clang
  - gcc

dist: bionic

services:
  - xvfb

before_install:
  - sudo apt-get update -qq

install:
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

before_script:
  - export DISPLAY=:99.0

script:
  - if [ "${CC}" == "clang" ]; then export CC="clang" ; export CXX="clang++" ; echo "Rexported clang" ; fi
  - if [ "${CC}" == "gcc" ]; then export CC="g++" ; export CXX="g++" ; echo "Rexported gcc" ; fi
  - qmake -qt=qt5 arsenic.pro -spec linux-$CC
  - make
  - sudo make install
  - arsenic -e -p mysuperbadpassphrase screenshots/main_dark.png
  - arsenic -d -p mysuperbadpassphrase screenshots/main_dark.png.arsenic
  - ./tests/tests

