before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -y qt5-default qttools5-dev-tools #install necessary Qt files

script:
 - qmake -project
 - qmake arsenic.pro
 - make
