language: generic
compiler: g++
dist: trusty
sudo: required

before_install:
  # g++6
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  
  # Qt5
  - sudo apt-add-repository --yes ppa:beineri/opt-qt58-trusty
  - travis_wait 20 sudo apt-get -qq update

install:
  # g++6
  - sudo apt-get remove g++
  - sudo apt-get install build-essential
  - sudo apt-get install -qq g++-6

  # Qt5
  - travis_wait 20 sudo apt-get install --yes qt58base

env: CXX= "g++-6" -std=c++14 -Wall -Wno-error"

script:
 - qmake -project
 - qmake arsenic.pro
 - make
