dist: trusty
language: cpp
compiler: g++
sudo: true

before_install:  
  # Qt5
  - sudo apt-add-repository --yes ppa:beineri/opt-qt58-trusty
  - travis_wait 20 sudo apt-get -qq update

install:
  # Qt5
  - travis_wait 20 sudo apt-get install --yes qt58base
  - sudo apt-get install clang



script:
 - qmake
 - make
 - ./Arsenic
