language: generic

compiler:
  - gcc CXX=g++-5 CC=gcc-5
  - clang CXX=clang++-3.8 CC=clang-3.8

os: linux
sudo: required
dist: trusty

env:
  matrix:
    - QT_BASE=53
    - QT_BASE=54
    - QT_BASE=55
    - QT_BASE=56
    - QT_BASE=57

before_install:
  # run Coverity scans only once
  - if [ "${TRAVIS_BRANCH}" == "coverity_scan" ] && [ ${TRAVIS_JOB_NUMBER##*.} -gt 1 ]; then exit 0; fi
  - if [ "$QT_BASE" = "53" ]; then sudo add-apt-repository ppa:beineri/opt-qt532-trusty -y; fi
  - if [ "$QT_BASE" = "54" ]; then sudo add-apt-repository ppa:beineri/opt-qt542-trusty -y; fi
  - if [ "$QT_BASE" = "55" ]; then sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y; fi
  - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y; fi
  - if [ "$QT_BASE" = "57" ]; then sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y; fi
  - sudo apt-get update -qq
  
install:
  - sudo apt-get install -yqq qt${QT_BASE}base qt${QT_BASE}svg; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh
  - sudo apt-get install g++-5
  - sudo apt-get install clang-3.8


script:
 - qmake -project
 - qmake arsenic.pro
 - make
