## FindBotan.cmake
##
## Strategy:
##   1. Try to use the system-installed Botan 3 (via its CMake config).
##   2. If not found, download the version specified by BOTAN_FALLBACK_VERSION
##      and build a minimised amalgamation.
##
## Usage in CMakeLists.txt:
##
##    find_package(Botan 3 REQUIRED)
##
##    botan_generate(my_target
##        aead argon2 sha3 ...
##    )
##
##    target_link_libraries(MyTarget PRIVATE my_target)

cmake_minimum_required(VERSION 3.28)
include(FetchContent)
cmake_policy(SET CMP0135 NEW)

# Botan 3 version to download when no system Botan is found.
# Override with -DBOTAN_FALLBACK_VERSION=X.Y.Z at configure time.
set(BOTAN_FALLBACK_VERSION "3.12.0" CACHE STRING
    "Botan 3 version to download if no system Botan 3 is found")

# ── 1. Try the system-installed Botan (CONFIG mode skips this Find module) ───
if(Botan_FIND_VERSION)
    find_package(Botan ${Botan_FIND_VERSION} CONFIG QUIET)
else()
    find_package(Botan CONFIG QUIET)
endif()

if(Botan_FOUND)
    message(STATUS "Found system Botan: ${Botan_VERSION}")
    set(BOTAN_USE_SYSTEM TRUE  CACHE INTERNAL "")
    set(Botan_VERSION_STRING "${Botan_VERSION}")
else()
    # ── 2. Fall back: download and build amalgamation ────────────────────────
    message(STATUS "System Botan not found – will download ${BOTAN_FALLBACK_VERSION}")
    set(BOTAN_USE_SYSTEM FALSE CACHE INTERNAL "")
    set(Botan_VERSION_STRING "${BOTAN_FALLBACK_VERSION}")

    find_package(Python COMPONENTS Interpreter REQUIRED)

    set(_botan_url
        "https://github.com/randombit/botan/archive/refs/tags/${BOTAN_FALLBACK_VERSION}.tar.gz")

    file(DOWNLOAD "${_botan_url}" STATUS _dl_status)
    if(NOT _dl_status EQUAL 0)
        message(FATAL_ERROR
            "Could not reach Botan tarball (status=${_dl_status}): ${_botan_url}")
    endif()

    FetchContent_Declare(botan_upstream URL "${_botan_url}")
    FetchContent_MakeAvailable(botan_upstream)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Botan DEFAULT_MSG Botan_VERSION_STRING)

# ── botan_generate(TARGET_NAME module1 module2 ...) ──────────────────────────
#
# Creates a CMake target TARGET_NAME backed either by the system library
# or by a freshly-generated Botan amalgamation.
#
function(botan_generate TARGET_NAME MODULES)

    if(BOTAN_USE_SYSTEM)

        # Generate a botan_all.h shim in the caller's binary directory so that
        # existing '#include "botan_all.h"' directives continue to work.
        set(_shim "${CMAKE_CURRENT_BINARY_DIR}/botan_all.h")
        file(WRITE "${_shim}"
"#pragma once\n"
"// Auto-generated shim – redirects to system Botan 3 headers.\n"
"// Do not edit; regenerated by cmake/FindBotan.cmake.\n"
"#include <botan/aead.h>\n"
"#include <botan/argon2.h>\n"
"#include <botan/mac.h>\n"
"#include <botan/mem_ops.h>\n"
"#include <botan/argon2fmt.h>\n"
"#include <botan/auto_rng.h>\n"
"#include <botan/cipher_mode.h>\n"
"#include <botan/data_src.h>\n"
"#include <botan/exceptn.h>\n"
"#include <botan/hash.h>\n"
"#include <botan/hex.h>\n"
"#include <botan/pem.h>\n"
"#include <botan/pwdhash.h>\n"
"#include <botan/rng.h>\n"
"#include <botan/secmem.h>\n"
"#include <botan/sodium.h>\n"
"#include <botan/symkey.h>\n"
"#include <botan/system_rng.h>\n"
"#include <botan/version.h>\n"
        )

        add_library(${TARGET_NAME} INTERFACE)
        target_link_libraries(${TARGET_NAME} INTERFACE Botan::Botan)
        # Expose the directory containing the shim so '#include "botan_all.h"' resolves.
        target_include_directories(${TARGET_NAME} INTERFACE "${CMAKE_CURRENT_BINARY_DIR}")

    else()

        # ── Amalgamation build from downloaded source ────────────────────────
        foreach(module_index RANGE 1 ${ARGC}-2)
            list(APPEND _modules_list ${ARGV${module_index}})
            if(ARGV${module_index} STREQUAL "pkcs11")
                set(PKCS11_ENABLED ON)
            endif()
        endforeach()
        list(JOIN _modules_list "," _enable_modules)

        set(_cc_id "${CMAKE_CXX_COMPILER_ID}")
        string(TOLOWER "${_cc_id}" _cc_id)
        if(_cc_id STREQUAL "gnu")
            set(_cc_id "gcc")
        elseif(_cc_id STREQUAL "appleclang")
            set(_cc_id "clang")
        endif()

        # Pass explicit --cpu when cross-compiling (e.g. arm64 host → x86_64 target).
        # Without it configure.py detects the host CPU and emits host-arch assembly.
        # Also pass --cc-abi-flags so configure.py's compiler probe targets the right
        # arch: on Apple Silicon the probe otherwise runs natively as arm64 and
        # conflicts with --cpu=x86_64. With -arch x86_64 the probe binary runs via
        # Rosetta 2 (available on all GitHub Actions macOS runners) and reports x86_64.
        set(_botan_cpu_args "")
        if(APPLE AND CMAKE_OSX_ARCHITECTURES)
            list(LENGTH CMAKE_OSX_ARCHITECTURES _narch)
            if(_narch EQUAL 1)
                list(GET CMAKE_OSX_ARCHITECTURES 0 _osx_arch)
                if(_osx_arch STREQUAL "x86_64")
                    list(APPEND _botan_cpu_args "--cpu=x86_64")
                    list(APPEND _botan_cpu_args "--cc-abi-flags=-arch x86_64")
                elseif(_osx_arch STREQUAL "arm64")
                    list(APPEND _botan_cpu_args "--cpu=aarch64")
                endif()
            endif()
        endif()

        add_custom_command(
            OUTPUT botan_all.cpp botan_all.h
            COMMENT "Generating Botan amalgamation files botan_all.cpp and botan_all.h"
            COMMAND ${Python_EXECUTABLE}
                ${botan_upstream_SOURCE_DIR}/configure.py
                --quiet
                --cc-bin=${CMAKE_CXX_COMPILER}
                --cc=${_cc_id}
                $<$<BOOL:${MINGW}>:--os=mingw>
                ${_botan_cpu_args}
                --amalgamation
                --minimized-build
                --disable-shared
                --enable-modules=${_enable_modules}
        )

        add_library(${TARGET_NAME} SHARED)
        target_compile_features(${TARGET_NAME} PUBLIC cxx_std_20)
        target_sources(${TARGET_NAME}
            PUBLIC  "${CMAKE_CURRENT_BINARY_DIR}/botan_all.h"
            PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/botan_all.cpp"
        )
        target_include_directories(${TARGET_NAME} INTERFACE "${CMAKE_CURRENT_BINARY_DIR}")
        target_link_libraries(${TARGET_NAME} PRIVATE
            $<$<NOT:$<BOOL:${MSVC}>>:pthread>)
        set_target_properties(${TARGET_NAME} PROPERTIES
            POSITION_INDEPENDENT_CODE ON
            WINDOWS_EXPORT_ALL_SYMBOLS ON
        )

        if(PKCS11_ENABLED)
            file(COPY "${botan_upstream_SOURCE_DIR}/src/lib/prov/pkcs11/pkcs11.h"
                 DESTINATION "${CMAKE_CURRENT_BINARY_DIR}")
            file(COPY "${botan_upstream_SOURCE_DIR}/src/lib/prov/pkcs11/pkcs11f.h"
                 DESTINATION "${CMAKE_CURRENT_BINARY_DIR}")
            file(COPY "${botan_upstream_SOURCE_DIR}/src/lib/prov/pkcs11/pkcs11t.h"
                 DESTINATION "${CMAKE_CURRENT_BINARY_DIR}")
            target_include_directories(${TARGET_NAME} PRIVATE
                "${botan_upstream_SOURCE_DIR}/src/lib/prov/pkcs11")
        endif()

    endif()
endfunction()
